import { setRevalidateHeaders } from "next/dist/server/send-payload";
import { getRouteMatcher } from "next/dist/shared/lib/router/utils/route-matcher";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import RoomRow from "../../components/display-rooms/RoomRow";
import CreateRoomForm from "../../components/home/CreateRoomForm";

export default function Home() {
  const [rooms, setRooms] = useState(undefined);

  useEffect(() => {
    fetch(process.env.NEXT_PUBLIC_SERVER_HOST + "/get-rooms", {
      method: "GET",
    })
      .then((response) => response.json())
      .then((data) => setRooms(data));
  }, []);

  return (
    <div className="p-4 flex flex-col gap-4 lg:flex-row">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="overflow-hidden rounded border border-black lg:self-start lg:flex-1">
        <div className=" bg-gray-200 p-2 border-b border-black">
          Active rooms
        </div>
        <div className=" bg-gray-300 p-4">
          <table className="w-full">
            <thead className="">
              <tr className=" border-b border-black ">
                <th className=" text-left pr-4">Room</th>
                <th className=" text-left pr-4">Creator</th>
                <th className=" text-left ">Game</th>
              </tr>
            </thead>
            <tbody className="">
              {rooms &&
                rooms.map((room) => (
                  <RoomRow
                    key={room.id}
                    id={room.id}
                    room={room.name}
                    creator={room.creator}
                    game={room.game}
                  />
                ))}
            </tbody>
          </table>
        </div>
      </section>

      <CreateRoomForm />
    </div>
  );
}
